### ISSUE TITLE
AttributeError when exporting a model in fastai2==0.0.11

### ISSUE THREAD

**Issue by jakubLangr** [fastai/fastai2#117]
This functionality used to work so just adding it here, as a possible regression:

It is a trained u-net model with pytorch 1.4.0 and fastai2==0.0.11.

To replicate, just put this line at the end of the `camvid` example.

EDIT: same thing with 0.0.8 and pytorch 1.2.0 works.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-462cbf4b35db> in <module>()
----> 1 learn.export('/efs/models/sem-seg-5')

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai2/learner.py in export(self, fname)
    609         if hasattr(self,'progress'): self.progress.mbar = master_bar(list(range(n)))
    610         aug_preds = []
--> 611         for i in self.progress.mbar if hasattr(self,'progress') else range(n):
    612             self.epoch = i #To keep track of progress on mbar since the progress callback will use self.epoch
    613             aug_preds.append(self.get_preds(ds_idx)[0][None])

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    326 
    327     If :attr:`map_location` is a :class:`torch.device` object or a string contraining
--> 328     a device tag, it indicates the location where all tensors should be loaded.
    329 
    330     Otherwise, if :attr:`map_location` is a dict, it will be used to remap location tags

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py in _legacy_save(obj, f, pickle_module, pickle_protocol)
    399             location = map_location.get(location, location)
    400             return default_restore_location(storage, location)
--> 401     elif isinstance(map_location, _string_classes):
    402         def restore_location(storage, location):
    403             return default_restore_location(storage, map_location)

AttributeError: Can't pickle local object 'combine_scheds.<locals>._inner'
```

**Comment by sgugger** [comment]
Be careful of not using lambda functions if you want to export your Learner since they can't pickle.

In the example you point, you need to change the `get_y` to define a real function (preferably in a utils module that you can import on your training machine and your inference machine) so that it can be serialized (python does not serialize the code, only the name of the function and where it comes from).

**Comment by jakubLangr** [comment]
Hi @sgugger are you 100% sure that is the case here? 

Couple of reasons why I have doubts:
* I have double-checked and there are no `lambda` functions anywhere in my script
* This error does *not* happen on `0.0.8`
* I have seen the lambda error and it looks different

**Comment by sgugger** [comment]
The example you cite as a reproducer works once I replace the lambda by a function, that's why I closed the issue. Please reopen with a reproducer with no lambdas and I can look into it, but I can't fix what I can't see ;)

**Comment by jakubLangr** [comment]
Hi @sgugger the same error happens on camvid if you add:
`learn.export('test')` after the first `show_results()`
```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-28-b19b8ed13fc9> in <module>()
----> 1 learn.export('test')

4 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _save(obj, f, pickle_module, pickle_protocol)
    330     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    331     pickler.persistent_id = persistent_id
--> 332     pickler.dump(obj)
    333 
    334     serialized_storage_keys = sorted(serialized_storages.keys())

PicklingError: Can't pickle <function <lambda> at 0x7fb217b6bd08>: attribute lookup <lambda> on __main__ failed
```

**Comment by jakubLangr** [comment]
Ok I don't have access to the same instance right now. Will try to replicate once I am back on it

**Comment by sgugger** [comment]
For what it's worth, I just tried an export after a show_results on the camvid example in the tutorial transfer learning notebook, and it worked fine.

**Comment by jakubLangr** [comment]
Hmm, strange. Might be something with the environment I am using. Will do some digging. Thanks for getting back to me :)

**Comment by jakubLangr** [comment]
Okay so just tried replicating it:

* pytorch 1.4.0
* fastai2 0.0.11 (from pypi)
* camvid example with no changes except include `learn.export('test.pkl')` after the first `fit_one_cycle`

If I include `learn.export('test')`, I get the following error instead:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-b19b8ed13fc9> in <module>()
----> 1 learn.export('test')

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fastai2/learner.py in export(self, fname)
    480     old_dbunch = self.dls
    481     self.dls = self.dls.new_empty()
--> 482     state = self.opt.state_dict()
    483     self.opt = None
    484     with warnings.catch_warnings():

AttributeError: 'NoneType' object has no attribute 'state_dict'
```

**Comment by sgugger** [comment]
There is definitely something wron with your installation as:
- fastai2 works perfectly with PyTorch 1.3.1 or 1.4.0 (1.3 is the minimum required version)
- everything you say runs absolutely fine on my side, provided the two lambda are replaced by regular functions.

You should do a fresh install (use the dev install for fastai2 and fastcore to have the latest).
